# \u4E0D\u63A8\u8350: \u5F00\u542Fdebug\u6A21\u5F0F\uFF0C\u8F93\u51FA\u8C03\u8BD5\u4FE1\u606F\uFF0C\u5E38\u7528\u4E8E\u68C0\u67E5\u7CFB\u7EDF\u8FD0\u884C\u72B6\u51B5
# debug: true

# \u8BBE\u7F6E\u65E5\u5FD7\u7EA7\u522B\uFF0Croot\u8868\u793A\u6839\u8282\u70B9\uFF0C\u5373\u6574\u4F53\u5E94\u7528\u65E5\u5FD7\u7EA7\u522B
logging:
  # \u8BBE\u7F6E\u5206\u7EC4
  group:
    ebank: com.itheima.controller,com.itheima.service,com.itheima.dao
    iservice: com.alibaba
  level:
    # \u9ED8\u8BA4info
    root: info
    # \u8BBE\u7F6E\u67D0\u4E2A\u5305\u7684\u65E5\u5FD7\u7EA7\u522B
    # com.itheima.controller: debug
    # \u8BBE\u7F6E\u5206\u7EC4\uFF0C\u5BF9\u67D0\u4E2A\u7EC4\u8BBE\u7F6E\u65E5\u5FD7\u7EA7\u522B
    ebank:
  pattern:
    # console: "%d - %m%n"
    console: "%d %clr(%5p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"