country: china
user1:
  name: Jack
  age: 12
likes:
  - game
  - music
  - sleep
users:
  -
    name: G
    age: 12
  -
    name: F
    age: 13
baseDir: /usr/lib
# 使用${属性名}引用数据
tempDir: ${baseDir}/maven
# 使用引号包囊的字符串，其中的转义字符可以生效
diffDir: "${baseDir}/t /t1 /t2"

# 创建类，用于封装下面的数据
# 由spring帮我们去加载数据到对象中，一定要告诉spring加载这组信息
# 使用时候从spring中直接获取信息使用
datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/springboot_db
  username: root
  password: root666123
server:
  port: 8888
#  servlet:
#    context-path: /test