# \u5E94\u7528\u73AF\u5883
# \u516C\u5171\u914D\u7F6E
spring:
  profiles:
    active: dev
---
# \u8BBE\u7F6E\u73AF\u5883
# \u751F\u4EA7\u73AF\u5883
spring:
  config:
    activate:
      on-profile: pro
server:
  port: 80
---
# \u5F00\u53D1\u73AF\u5883
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 81
---
# \u6D4B\u8BD5\u73AF\u5883
spring:
  config:
    activate:
      on-profile: test
server:
  port: 82